{{- $root := . -}}
{{- range $name, $config := .Values.CertificateIssuers -}}
{{- if $config.enabled }}
{{- if not (empty $config.clusterIssuers) }}
{{- range $config.clusterIssuers }}
---
# raw issuer: {{ . | toJson }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
{{ template "common.metadata" (dict "data" . "root" $) }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- if not (empty $config.Issuers) }}
{{- range $config.Issuers }}
---
# raw issuer: {{ . | toJson }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
apiVersion: cert-manager.io/v1
kind: Issuer
{{ template "common.metadata" (dict "data" . "root" $) }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
